export const ESTADOS = [
    { label: 'Acre', value: 'Acre', selected: true },
    { label: 'Alagoas', value: 'Alagoas', selected: false },
    { label: 'Amapá', value: 'Amapá', selected: false },
    { label: 'Amazonas', value: 'Amazonas', selected: false },
    { label: 'Bahia', value: 'Bahia', selected: false },
    { label: 'Ceará', value: 'Ceará', selected: false },
    { label: 'Distrito Federal', value: 'Distrito Federal', selected: false },
    { label: 'Espírito Santo', value: 'Espírito Santo', selected: false },
    { label: 'Goiás', value: 'Goiás', selected: false },
    { label: 'Maranhão', value: 'Maranhão', selected: false },
    { label: 'Mato Grosso', value: 'Mato Grosso', selected: false },
    { label: 'Mato Grosso do Sul', value: 'Mato Grosso do Sul', selected: false },
    { label: 'Minas Gerais', value: 'Minas Gerais', selected: false },
    { label: 'Pará', value: 'Pará', selected: false },
    { label: 'Paraíba', value: 'Paraíba', selected: false },
    { label: 'Paraná', value: 'Paraná', selected: false },
    { label: 'Pernambuco', value: 'Pernambuco', selected: false },
    { label: 'Piauí', value: 'Piauí', selected: false },
    { label: 'Rio de Janeiro', value: 'Rio de Janeiro', selected: false },
    { label: 'Rio Grande do Norte', value: 'Rio Grande do Norte', selected: false },
    { label: 'Rio Grande do Sul', value: 'Rio Grande do Sul', selected: false },
    { label: 'Rondônia', value: 'Rondônia', selected: false },
    { label: 'Roraima', value: 'Roraima', selected: false },
    { label: 'Santa Catarina', value: 'Santa Catarina', selected: false },
    { label: 'São Paulo', value: 'São Paulo', selected: false },
    { label: 'Sergipe', value: 'Sergipe', selected: false },
    { label: 'Tocantins', value: 'Tocantins', selected: false },
];
